name = "local-assets-worker"
main = "worker-proxy.js"
compatibility_date = "2024-04-01"

[vars]
ACCOUNT_ID = "460259198d4a56e53034a2bbe1f915c7"
R2_BUCKET_NAME = "venue-assets"

# Set these using 'npx wrangler secret put' for security
# R2_ACCESS_KEY_ID = "..."
# R2_SECRET_ACCESS_KEY = "..."
# API_KEY = "..."
